### ISSUE TITLE
漏斗矿车可以直接通过领地边界下的方块卡入领地吸走边界容器内的物品

### ISSUE THREAD

**Issue by chenjunfu2** [zly2006/Enclosure#11]
**描述BUG**
漏斗矿车可以直接通过领地边界下的方块卡入领地吸走边界容器内的物品。

**重现**
在领地边界处放一个箱子、潜影盒，箱子是不完整方块，因此可以使用倾斜铁轨将漏斗矿车直接卡入下面的方块吸走箱子内物品，潜影盒则需要使用转弯铁轨放上矿车卡入下面的方块并吸走盒内物品。

**预期行为**
漏斗矿车即便卡入领地内箱子、潜影盒下方，也不应该吸走内部的物品。

**屏幕截图**
![QQ图片20230505192118](https://user-images.githubusercontent.com/64954184/236456960-0d809847-57f6-46d6-ad81-467d447672d7.png)
![QQ图片20230505192129](https://user-images.githubusercontent.com/64954184/236456999-bfb31960-fad5-47d7-8582-ad8298a00b90.png)
![QQ图片20230505192132](https://user-images.githubusercontent.com/64954184/236457016-f85cbbdd-6b57-4cab-b0cd-32012ffce9a1.png)
![QQ图片20230505192135](https://user-images.githubusercontent.com/64954184/236457029-3d4d9a35-a689-40a2-8b2c-a2c80cec33a9.png)
![QQ图片20230505192139](https://user-images.githubusercontent.com/64954184/236457039-16ca83dc-4f0b-4023-846d-ed4f3fd6aacc.png)
![QQ图片20230505192142](https://user-images.githubusercontent.com/64954184/236457067-60ed37c8-d31b-4ae4-8ded-145b013eb7fd.png)
![QQ图片20230505192205](https://user-images.githubusercontent.com/64954184/236457127-09476a93-39f9-4ea0-86a1-e80102b33bca.png)
![QQ图片20230505192208](https://user-images.githubusercontent.com/64954184/236457168-5de77b0e-7ce0-41c9-8b1f-ff3bd8b9d4a0.png)
![QQ图片20230505192211](https://user-images.githubusercontent.com/64954184/236457250-efe7c7e7-b398-4f29-8bc1-665d6266c541.png)

**环境**
 - 操作系统：Windows 10
 - MC版本：1.19.4-Fabric 0.14.17
 - MOD版本：enclosure-0.1-mc1.19.4

**MC Mod列表**
+ [领地] enclosure-0.1-mc1.19.4.jar
+ fabric-api-0.75.3+1.19.4.jar

- [√] 我确定这个bug在最新版本的Enclosure中会出现。
- [√] 我使用的是官方的版本，而不是这个仓库的分支。
- [√] 我使用的Minecraft版本仍在维护。

**其他上下文**
可以打开漏斗矿车直接拿取物品，也可以在矿车漏出领地外侧的部分下面，放上漏斗吸走矿车内物品。

**Comment by chenjunfu2** [comment]
这是潜影盒的做法，使用拐弯铁轨：
![QQ图片20230505192457](https://user-images.githubusercontent.com/64954184/236457499-9895a0b0-a2fe-4695-830b-0da3456f2419.png)
![QQ图片20230505192503](https://user-images.githubusercontent.com/64954184/236457516-5d9b815f-bb55-45af-86a4-ad13d0c1760d.png)
![QQ图片20230505192507](https://user-images.githubusercontent.com/64954184/236457523-e435593c-bf01-4022-9104-9bb107451946.png)
![QQ图片20230505192511](https://user-images.githubusercontent.com/64954184/236457529-e6ecfbb0-27d2-4c6c-b505-a9b4af7cf959.png)
![QQ图片20230505192514](https://user-images.githubusercontent.com/64954184/236457538-1a3063fc-7f50-4f82-a98a-f9c2c60e525f.png)
![QQ图片20230505192518](https://user-images.githubusercontent.com/64954184/236457543-637fad75-fe61-4fcd-8369-27b4397474b2.png)
![QQ图片20230505192542](https://user-images.githubusercontent.com/64954184/236457555-d9fabecb-bca6-4106-9ce8-359b6e67a58d.png)
![QQ图片20230505192545](https://user-images.githubusercontent.com/64954184/236457565-cabd7753-f35f-4dad-a601-299817429cf8.png)
![QQ图片20230505192547](https://user-images.githubusercontent.com/64954184/236457580-6e813394-538a-4388-a14d-b336e2ff9ea6.png)

**Comment by zly2006** [comment]
将会添加两条规则来处理：
- [ ] 独立的hopper权限，作用域领地，可以阻止***一部分***在领地外的漏斗矿车吸取物品
- [ ] 所有实体添加push权限，阻止实体被推过领地边界
