### ISSUE TITLE
在没有allay权限在与悦灵右键交互的时候，一次右键会出现四个相同的，提示你没有allay权限的信息

### ISSUE THREAD

**Issue by chenjunfu2** [zly2006/Enclosure#13]
**描述BUG**
在没有allay权限在与悦灵右键交互的时候，一次右键会出现四个相同的，提示你没有allay权限的信息。

**重现**
删除自己的allay权限和op，在领地内右键一次悦灵。

**预期行为**
出现一个提示你没有allay权限的信息。

**屏幕截图**
![QQ图片20230505193019](https://user-images.githubusercontent.com/64954184/236459224-788244dc-34b2-4c83-a556-87206ba35c1e.png)
![QQ图片20230505193023](https://user-images.githubusercontent.com/64954184/236459236-40ef5f5f-cba9-4713-afaa-04050330d574.png)

**环境**
 - 操作系统：Windows 10
 - MC版本：1.19.4-Fabric 0.14.17
 - MOD版本：enclosure-0.1-mc1.19.4

**MC Mod列表**
+ [领地] enclosure-0.1-mc1.19.4.jar
+ fabric-api-0.75.3+1.19.4.jar

- [√] 我确定这个bug在最新版本的Enclosure中会出现。
- [√] 我使用的是官方的版本，而不是这个仓库的分支。
- [√] 我使用的Minecraft版本仍在维护。

**其他上下文**
无

**Comment by sakurawald** [comment]
It's because the interact is from your MAIN_HAND and OFF_HAND. This should be only triggered once.
Not actually affect anything.

**Comment by chenjunfu2** [comment]
ok
