### ISSUE TITLE
在没有领地vehicle权限的情况下仍然能往领地内放置船、箱船

### ISSUE THREAD

**Issue by chenjunfu2** [zly2006/Enclosure#15]
**描述BUG**
在没有领地vehicle权限的情况下仍然能往领地内放置船、箱船。

**重现**
删除自己的vehicle权限和op，拿着船、箱船往领地内右键放置。

**预期行为**
放置操作失败。

**屏幕截图**
![QQ图片20230505193121](https://user-images.githubusercontent.com/64954184/236460726-9b225327-9b46-4d73-bf53-9df18e8f73da.png)
![QQ图片20230505193125](https://user-images.githubusercontent.com/64954184/236460774-c5392d38-c03a-4e9d-af20-9faa01ef581c.png)

**环境**
 - 操作系统：Windows 10
 - MC版本：1.19.4-Fabric 0.14.17
 - MOD版本：enclosure-0.1-mc1.19.4

**MC Mod列表**
+ [领地] enclosure-0.1-mc1.19.4.jar
+ fabric-api-0.75.3+1.19.4.jar

- [√] 我确定这个bug在最新版本的Enclosure中会出现。
- [√] 我使用的是官方的版本，而不是这个仓库的分支。
- [√] 我使用的Minecraft版本仍在维护。

**其他上下文**
会出现一个提示你没有vehicle权限的信息，但是放置船、箱船的操作仍然成功。

**Comment by zly2006** [comment]
使用你的modlist复现失败，请提供更多信息：
1. 退出重进服务器船是否还存在？
2. 信息和modlist是否完整准确？

**Comment by chenjunfu2** [comment]
已确认，退出重进后船还在，信息喝modlist完全准确，经过测试，需要人在领地外往领地内放置，如果人在领地内往领地内放置确实是无法放出的

**Comment by chenjunfu2** [comment]
这是在领地外往领地内放置，提示无权限但是放置成功（不符合预期行为）：
![QQ图片20230506124852](https://user-images.githubusercontent.com/64954184/236600500-521d60c4-7948-4280-89c0-c6668e741e4b.png)
这是在领地内往领地内放置，提示无权限并且放置失败（符合预期行为）：
![QQ图片20230506124855](https://user-images.githubusercontent.com/64954184/236600526-c7d424a3-6eb2-4156-a88f-50990dc5f8e1.png)

**Comment by Hti-0683** [comment]
我这里也能复现，并且重进后船还在
![java_tpmKPH1Npr](https://user-images.githubusercontent.com/66823771/236600659-1dbfc577-765d-4c83-8520-3ee1b1c5cce2.png)
