### ISSUE TITLE
无place_block权限情况下也能在领地内点火

### ISSUE THREAD

**Issue by chenjunfu2** [zly2006/Enclosure#17]
手拿打火石，在无place_block权限和op权限的情况下：
对着地面右键会点火失败，显示无place_block权限
![1](https://user-images.githubusercontent.com/64954184/236600872-31e3f6c3-c69c-4c68-bd1c-17c7d5f40ffc.png)
对着任意不可交互方块侧面右键，则会在方块侧面成功点火
![2](https://user-images.githubusercontent.com/64954184/236600910-719f042a-7b79-4620-88b2-ff21196313f5.png)
对着任意可交互方块侧面右键，显示无方块交互权限，但是按住潜行按键再右键，则会在可交互方块侧面成功点火
![3](https://user-images.githubusercontent.com/64954184/236600965-857dc505-5f81-4655-99a4-651b439b8c5b.png)

**Comment by chenjunfu2** [comment]
实测火焰弹也可以，不只是打火石

**Comment by zly2006** [comment]
请测试其在最新开发版本是否还出现

**Comment by chenjunfu2** [comment]
已解决
