### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by BrGef** [zly2006/Enclosure#25]
### Check the following items before submitting this issue.

- [x] I am sure that this bug happens in the newest version of Enclosure.
- [x] I am using the official Enclosure, not a fork from this repo.
- [ ] I am using a Minecraft version that is still being maintained.

### Describe the bug

创建领地名时在中间加个点会
导致删除领地，tp领地还有设置领地权限 都会显示找不到领地
使用服务器op权限也会显示找不到领地

创建子领地也是这样，只要在中间加点就会产生这个bug

### To Reproduce

创建领地时在中间加点即可

### Expected behavior

无法删除领地.tp领地.也无法设置领地权限

### Screenshots

![image](https://github.com/zly2006/Enclosure/assets/101499922/862ebd67-4438-4aad-ba43-2e5e7a8f2af3)

### Environment

windows 11 

### Mod list

无

### Log (Optional)

无

**Comment by zly2006** [comment]
实际上这个领地应该是非法的——在之前的版本中，创建领地时op并没有应用对于领地名称和长度的检查

1.1会导致系统试图寻找“1”中的子领地“1”，导致失败

可以deop之后看看还能不能创建

**Comment by BrGef** [comment]
> 实际上这个领地应该是非法的——在之前的版本中，创建领地时op并没有应用对于领地名称和长度的检查
> 
> 1.1会导致系统试图寻找“1”中的子领地“1”，导致失败
> 
> 可以deop之后看看还能不能创建

没op确定不能创建，但创建子领地没op也可以加点，而且创建后不删除父领地就也无法使用这个子领地，建议创建子领地也过滤掉点

**Comment by BrGef** [comment]
> 实际上这个领地应该是非法的——在之前的版本中,创建领地时外科手术并没有应用对于领地名称和长度的检查
> 
> 1.1会导致系统试图寻找"1"中的子领地"1",导致失败
> 
> 可以deop之后看看还能不能创建


我又试了用重命名方法，是没有过虑的，不用op也能改，dm而且改了还是和之前一样无法通过op删除领地
![image](https://github.com/zly2006/Enclosure/assets/101499922/1c454d8b-1b00-4e4d-a2e4-50a6d2f190ae)
