### ISSUE TITLE
[BUG] 在服务器中左键使用木锄点击任何方块时，会发生客户端崩溃

### ISSUE THREAD

**Issue by disymayufei** [zly2006/Enclosure#28]
### Check the following items before submitting this issue.

- [X] I am sure that this bug happens in the newest version of Enclosure.
- [X] I am using the official Enclosure, not a fork from this repo.
- [X] I am using a Minecraft version that is still being maintained.

### Describe the bug

在服务器中左键使用木锄点击任何方块时，会发生客户端崩溃，并产生以下报错：

java.lang.NullPointerException: Unexpected error
	at com.github.zly2006.enclosure.listeners.SessionListener.interact(SessionListener.kt:36)
	at net.fabricmc.fabric.api.event.player.AttackBlockCallback.lambda$static$0(AttackBlockCallback.java:51)
	at net.minecraft.class_636.fabric_fireAttackBlockCallback(class_636.java:2168)
	at net.minecraft.class_636.handler$con000$fabric-events-interaction-v0$attackBlock(class_636.java:2156)
	at net.minecraft.class_636.method_2910(class_636.java:150)
	at net.minecraft.class_310.method_1536(class_310.java:1736)
	at net.minecraft.class_310.method_1508(class_310.java:2049)
	at net.minecraft.class_310.method_1574(class_310.java:1883)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### To Reproduce

1. 进入服务器
2. 手持木锄左键点击任何方块
3. bug产生，客户端崩溃

### Expected behavior

客户端不会崩溃，可用木锄正常选取范围

### Environment

- OS: Windows 11
- MC Version: 1.20.1
- Version 0.33+1.20.1

### Mod list

appleskin: AppleSkin 2.5.0+mc1.20
architectury: Architectury 9.1.12
authme: Auth Me 7.0.1+1.20
autofish: Autofish 0.9.10-SNAPSHOT
badpackets: Bad Packets 0.4.1
bedrockminer: Bedrock Miner 1.20.1-1.1.7
better-selection: Better Text Selection 1.1.1
betterbeds: Better Beds 1.3.0
betterf3: BetterF3 7.0.1
betterpingdisplay: Better Ping Display 1.1.1
carpet: Carpet Mod 1.4.112+v230608
carpet-sls-addition: Carpet SLS Addition 0.6.2
	fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
carpet-tctc-addition: Carpet TCTC Addition 2.2.196+f4bc3a3-beta
carpet-tis-addition: Carpet TIS Addition 1.50.1
	conditional-mixin: conditional mixin 0.3.2
chat_heads: Chat Heads 0.10.14
cloth-config: Cloth Config v11 11.0.99
	cloth-basic-math: cloth-basic-math 0.6.1
continuity: Continuity 3.0.0-beta.3+1.20.1
ctrl-q: Ctrl Q 1.9
cull-less-leaves: Cull Less Leaves 1.2.0
customskinloader: CustomSkinLoader 15.0-SNAPSHOT-9
debugify: Debugify 1.20.1+2.0
durability101: Durability101 0.0.5
eatinganimationid: Eating Animation 1.9.4+1.20
enclosure: Enclosure 0.3.3+1.20
enhancedblockentities: Enhanced Block Entities 0.9+1.20
	advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
	spruceui: SpruceUI 5.0.0+1.20
entityculling: EntityCulling-Fabric 1.6.2-mc1.20
fabric-api: Fabric API 0.87.0+1.20.1
	fabric-api-base: Fabric API Base 0.4.30+7abfd51577
	fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
	fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
	fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
	fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
	fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
	fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
	fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
	fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
	fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
	fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
	fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
	fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
	fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.2+1e61dba177
	fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
	fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
	fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
	fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
	fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
	fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
	fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
	fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
	fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
	fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
	fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
	fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
	fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
	fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
	fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
	fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
	fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
	fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
	fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
	fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
	fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
	fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
	fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.2+6bdb2ed077
	fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.2+6bdb2ed077
	fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
	fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
	fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
	fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
	fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
	fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
	fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
	fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
	fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
	fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
	fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
	fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
	org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
	org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
	org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
	org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
	org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
	org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
	org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
	org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
	org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
	org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
	org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
fabricloader: Fabric Loader 0.14.21
fabricskyboxes: FabricSkyBoxes 0.7.2+mc1.20.1
fallingleaves: Falling Leaves 1.15.2+1.20.1
faster_entity_animations: FastAnim 1.6
fastload: Fast Load 3.4.0
	fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
	fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
	fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
	fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
fastrandom: fastrandom 1.0-proto
ferritecore: FerriteCore 6.0.0
gammautils: Gamma Utils 1.7.16
imblocker: IMBlocker 4.0.5
immediatelyfast: ImmediatelyFast 1.1.13
	net_lenni0451_reflect: Reflect 1.1.0
indium: Indium 1.0.25+mc1.20.1
inventoryprofilesnext: Inventory Profiles Next 1.10.7
iris: Iris 1.6.8
	io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
	org_anarres_jcpp: jcpp 1.4.14
	org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
itemscroller: Item Scroller 0.19.2
java: OpenJDK 64-Bit Server VM 17
lambdynlights: LambDynamicLights 2.3.1+1.20
	pride: Pride Lib 1.2.0+1.19.4
libipn: libIPN 4.0.0
litematica: Litematica 0.14.3
lithium: Lithium 0.11.2
magiclib: MagicLib 0.7.336+05361cf-stable
	magiclib-1_20: MagicLib for 1.20.1 0.7.336+05361cf-stable
malilib: MaLiLib 0.15.4
masa_gadget_mod: Masa Gadget 3.2.308+2c7a07f-stable
	masa_gadget_mod-1_20: Masa Gadget for 1.20.1 3.2.308+2c7a07f-stable
minecraft: Minecraft 1.20.1
minihud: MiniHUD 0.26.2-nyan.1
mod-loading-screen: Mod Loading Screen 1.0.1
	com_formdev_flatlaf: flatlaf 3.0
modmenu: Mod Menu 7.0.1
my-beloved-icon: my-beloved-icon 1.0-SNAPSHOT
nochatreports: No Chat Reports 1.20.1-v2.2.1
notenoughanimations: NotEnoughAnimations 1.6.4
ommc: Oh My Minecraft Client 0.5.282+2b353c9-beta
pca: Plusls Carpet Addition 0.3.163+a95078f-beta
reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.20.1-build.94
replaymod: Replay Mod 1.20.1-2.6.13
roughlyenoughitems: Roughly Enough Items 12.0.645
	error_notifier: Error Notifier 1.0.9
skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
sodium: Sodium 0.5.2
sodium-extra: Sodium Extra 0.5.1+mc1.20.1-build.112
	caffeineconfig: CaffeineConfig 1.3.0+1.17
	crowdin-translate: CrowdinTranslate 1.4+1.19.3
spark: spark 1.10.42
starlight: Starlight 1.1.2+fabric.42e9b6f
syncmatica: Syncmatica 1.20.1-0.3.9
tweakeroo: Tweakeroo 0.16.0
tweakmyclient: Tweak My Client 3.6.398+b6a4f1b-stable
	tweakmyclient-1_20: Tweak My Client for 1.20.1 3.6.398+b6a4f1b-stable
universal-shortcuts-mc: Universal Shortcuts 1.2.2
viafabric: ViaFabric 0.4.10+6-dev
	org_yaml_snakeyaml: snakeyaml 2.0
	viafabric-mc120: ViaFabric for 1.20 0.4.10+6-dev
	viaversion: ViaVersion 4.7.0
voicechat: Simple Voice Chat 1.20.1-2.4.21
worldedit: WorldEdit 7.2.15+6463-5ca4dff
worldeditcui: WorldEditCUI 1.20+01
wthit: wthit 8.3.1
xaerominimap: Xaero's Minimap 23.6.2
xaeroworldmap: Xaero's World Map 1.33.0
yet_another_config_lib_v3: YetAnotherConfigLib 3.1.0+1.20
	com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
	com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
	com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
	com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
	com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
	com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
zoomify: Zoomify 2.11.0
	com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
	com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
	dev_isxander_settxi_settxi-core: settxi-core 2.10.6
	dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6

**Comment by disymayufei** [comment]
最新版已修复

**Comment by WarSkyGod** [comment]
> 最新版已修复

并没有，还是会崩溃
[错误报告-2023-9-7_16.16.17.zip](https://github.com/zly2006/Enclosure/files/12546438/-2023-9-7_16.16.17.zip)

**Comment by SakuraWald** [comment]
> > 最新版已修复
> 
> 并没有，还是会崩溃 [错误报告-2023-9-7_16.16.17.zip](https://github.com/zly2006/Enclosure/files/12546438/-2023-9-7_16.16.17.zip)

Can confirm that this bug still not be fixed in 1.20.1 release version

**Comment by zly2006** [comment]
> Can confirm that this bug still not be fixed in 1.20.1 release version

Are you using the latest version 0.3.4?

**Comment by WarSkyGod** [comment]
这话题不是早结束了吗...谁又给翻出来了...

**Comment by sakurawald** [comment]
> > Can confirm that this bug still not be fixed in 1.20.1 release version
> 
> Are you using the latest version 0.3.4?

Another version that i build, it's like near 0.3.4.
Close this issue, and i will create another issue if something is confirmed.
