### ISSUE TITLE
Incorrectly assumes that non-client worlds are ServerWorld

### ISSUE THREAD

**Issue by TropheusJ** [zly2006/Enclosure#37]
On [this line](https://github.com/zly2006/Enclosure/blob/11965418d2c1f9ff751620b2760581324332c286/src/main/kotlin/com/github/zly2006/enclosure/ServerMain.kt#L262), the world is casted to `ServerWorld` after checking that `isClient` is false.
This is fine in vanilla, but Create breaks this assumption, causing a crash: https://github.com/Fabricators-of-Create/Create/issues/1433
This can be fixed by checking that the world is actually a `ServerWorld`. I'm not sure how this is done in Kotlin, but in java you just need to replace `world.isClient`  with `!(world instanceof ServerWorld)`.

**Comment by zly2006** [comment]
Thanks a lot for your report!

**Comment by zly2006** [comment]
Can confirm it has been fixed
