### ISSUE TITLE
[BUG] 1.20.4启动报错

### ISSUE THREAD

**Issue by liuchuanbo0128** [zly2006/Enclosure#38]
### Check the following items before submitting this issue.

- [X] I am sure that this bug happens in the newest version of Enclosure.
- [X] I am using the official Enclosure, not a fork from this repo.
- [x] I am using a Minecraft version that is still being maintained.

### Describe the bug

当我启动时，报错如下
Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod enclosure
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:514)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285)
	at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:512)
	... 4 more

### To Reproduce

启动fabric1.20.4服务器

### Expected behavior

修复下

### Environment

- OS: Windows10 LTSC
- MC Version: 1.20.4
- Version 0.3.6
-MCDR 2.12.3

### Mod list

![Screenshot_20240412_193313](https://github.com/zly2006/Enclosure/assets/102268403/5a291636-89c0-4e51-aee8-4fd6de0721c6)

### Log (Optional)

MCDReforged 2.12.3 is starting up
MCDReforged is open source, u can find it here: https://github.com/Fallen-Breath/MCDReforged
[MCDR] [19:28:44] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [19:28:44] [MainThread/INFO]: 编码 / 解码方式已设置为 utf8 / utf8
[MCDR] [19:28:44] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [19:28:44] [MainThread/INFO]: - plugins
[MCDR] [19:28:44] [MainThread/INFO]: 解析处理器已设置为 vanilla_handler
[MCDR] [19:28:44] [MainThread/INFO]: MCDReforged正于Python 3.11.0环境中运行
[MCDR] [19:28:44] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 allow_suicide@1.0.0 已加载
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 gamemode@1.1.0 已加载
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 info@0.2.0 已加载
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 minecraft_data_api@1.5.0 已加载
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.10.1 已加载
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 timed_quick_backup_multi@1.3.0 已加载
[MCDR] [19:28:44] [TaskExecutor/INFO]: 插件 where_is@2.2.0+build.12 已加载
[MCDR] [19:28:45] [TaskExecutor/INFO] [where_is]: 配置文件已加载
[MCDR] [19:28:45] [TaskExecutor/INFO] [gamemode]: 配置文件已加载
[MCDR] [19:28:45] [TaskExecutor/INFO] [info]: 配置文件已加载
[MCDR] [19:28:45] [TaskExecutor/INFO] [quick_backup_multi]: 配置文件已加载
[MCDR] [19:28:45] [TaskExecutor/INFO] [timed_quick_backup_multi]: 配置文件已加载
[MCDR] [19:28:45] [TaskExecutor/INFO]: 共加载: 7 个插件; 已加载插件数: 9
[MCDR] [19:28:45] [MainThread/INFO]: 正在启动服务端，启动参数为 "start.bat"
[MCDR] [19:28:45] [MainThread/INFO]: 服务端正在以 PID 4760 运行中
[MCDR] [19:28:45] [CheckUpdate/INFO]: MCDR 已为最新版
[Server] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[Server] [19:28:47] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.9
[Server] [19:28:47] [ForkJoinPool-1-worker-1/WARN]: Mod enclosure uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[Server] [19:28:47] [main/INFO]: Loading 110 mods:
[Server]        - c2me 0.2.0+alpha.11.58
[Server]           |-- c2me-base 0.2.0+alpha.11.58
[Server]           |-- c2me-client-uncapvd 0.2.0+alpha.11.58
[Server]           |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.58
[Server]           |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.58
[Server]           |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.58
[Server]           |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.58
[Server]           |-- c2me-notickvd 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-allocs 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-chunk-access 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-chunkio 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-math 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-scheduling 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-worldgen-general 0.2.0+alpha.11.58
[Server]           |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.58
[Server]           |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.58
[Server]           |-- c2me-rewrites-chunkio 0.2.0+alpha.11.58
[Server]           |-- c2me-server-utils 0.2.0+alpha.11.58
[Server]           |-- c2me-threading-chunkio 0.2.0+alpha.11.58
[Server]           |-- c2me-threading-lighting 0.2.0+alpha.11.58
[Server]           |-- c2me-threading-worldgen 0.2.0+alpha.11.58
[Server]           |-- com_electronwill_night-config_core 3.6.5
[Server]           |-- com_electronwill_night-config_toml 3.6.5
[Server]           |-- com_ibm_async_asyncutil 0.1.0
[Server]           |-- net_objecthunter_exp4j 0.4.8
[Server]           \-- org_threadly_threadly 7.0
[Server]        - carpet 1.4.128+v231205
[Server]        - easyauth 3.0.20
[Server]           |-- at_favre_lib_bcrypt 0.10.2
[Server]           |-- at_favre_lib_bytes 1.6.1
[Server]           |-- com_mysql_mysql-connector-j 8.2.0
[Server]           |-- de_mkammerer_argon2-jvm 2.11
[Server]           |-- de_mkammerer_argon2-jvm-nolibs 2.11
[Server]           |-- fabric-permissions-api-v0 0.2-SNAPSHOT
[Server]           |-- net_java_dev_jna_jna 5.13.0
[Server]           |-- org_iq80_leveldb_leveldb 0.12
[Server]           |-- org_iq80_leveldb_leveldb-api 0.12
[Server]           |-- org_mongodb_bson 4.11.1
[Server]           |-- org_mongodb_mongodb-driver-core 4.11.1
[Server]           |-- org_mongodb_mongodb-driver-sync 4.11.1
[Server]           |-- placeholder-api 2.3.0+1.20.3
[Server]           \-- server_translations_api 2.2.0+1.20.3-rc1
[Server]                \-- packet_tweaker 0.5.0+1.20.2-rc1
[Server]        - enclosure ${version}
[Server]        - essential_commands 0.35.0-mc1.20.4
[Server]           |-- ec-core 1.3.0-mc1.20.4
[Server]           |    |-- fabric-permissions-api-v0 0.2-SNAPSHOT
[Server]           |    |-- placeholder-api 2.3.0+1.20.3
[Server]           |    \-- playerabilitylib 1.9.0
[Server]           |-- fabric-permissions-api-v0 0.2-SNAPSHOT
[Server]           |-- org_yaml_snakeyaml 2.0
[Server]           |-- placeholder-api 2.3.0+1.20.3
[Server]           \-- playerabilitylib 1.9.0
[Server]        - fabric-api 0.97.0+1.20.4
[Server]           |-- fabric-api-base 0.4.37+78d798af4f
[Server]           |-- fabric-api-lookup-api-v1 1.6.50+82b1bb3e4f
[Server]           |-- fabric-biome-api-v1 13.0.17+78d798af4f
[Server]           |-- fabric-block-api-v1 1.0.17+3e2216cb4f
[Server]           |-- fabric-block-view-api-v2 1.0.5+78d798af4f
[Server]           |-- fabric-blockrenderlayer-v1 1.1.47+78d798af4f
[Server]           |-- fabric-client-tags-api-v1 1.1.8+78d798af4f
[Server]           |-- fabric-command-api-v1 1.2.42+f71b366f4f
[Server]           |-- fabric-command-api-v2 2.2.21+78d798af4f
[Server]           |-- fabric-commands-v0 0.2.59+df3654b34f
[Server]           |-- fabric-containers-v0 0.1.87+df3654b34f
[Server]           |-- fabric-content-registries-v0 5.0.16+78d798af4f
[Server]           |-- fabric-convention-tags-v1 1.5.11+78d798af4f
[Server]           |-- fabric-crash-report-info-v1 0.2.24+78d798af4f
[Server]           |-- fabric-data-attachment-api-v1 1.1.5+b90db5744f
[Server]           |-- fabric-data-generation-api-v1 13.2.5+5c0133444f
[Server]           |-- fabric-dimensions-v1 2.1.62+78d798af4f
[Server]           |-- fabric-entity-events-v1 1.6.2+09fc25014f
[Server]           |-- fabric-events-interaction-v0 0.7.2+389931eb4f
[Server]           |-- fabric-events-lifecycle-v0 0.2.75+df3654b34f
[Server]           |-- fabric-game-rule-api-v1 1.0.47+78d798af4f
[Server]           |-- fabric-item-api-v1 2.3.0+bcdd12964f
[Server]           |-- fabric-item-group-api-v1 4.0.27+ee30b13a4f
[Server]           |-- fabric-key-binding-api-v1 1.0.42+78d798af4f
[Server]           |-- fabric-keybindings-v0 0.2.40+df3654b34f
[Server]           |-- fabric-lifecycle-events-v1 2.3.1+a67ffb5d4f
[Server]           |-- fabric-loot-api-v2 2.1.10+78d798af4f
[Server]           |-- fabric-message-api-v1 6.0.6+78d798af4f
[Server]           |-- fabric-mining-level-api-v1 2.1.66+78d798af4f
[Server]           |-- fabric-model-loading-api-v1 1.0.9+78d798af4f
[Server]           |-- fabric-models-v0 0.4.8+9386d8a74f
[Server]           |-- fabric-networking-api-v1 3.1.8+2e5ac5484f
[Server]           |-- fabric-object-builder-api-v1 13.1.0+dba1195c4f
[Server]           |-- fabric-particles-v1 1.1.8+78d798af4f
[Server]           |-- fabric-recipe-api-v1 2.0.21+78d798af4f
[Server]           |-- fabric-registry-sync-v0 4.0.20+ee30b13a4f
[Server]           |-- fabric-renderer-api-v1 3.2.5+78d798af4f
[Server]           |-- fabric-renderer-indigo 1.5.5+78d798af4f
[Server]           |-- fabric-renderer-registries-v1 3.2.54+df3654b34f
[Server]           |-- fabric-rendering-data-attachment-v1 0.3.43+73761d2e4f
[Server]           |-- fabric-rendering-fluids-v1 3.1.2+e761c6694f
[Server]           |-- fabric-rendering-v0 1.1.57+df3654b34f
[Server]           |-- fabric-rendering-v1 3.2.1+6fd945a04f
[Server]           |-- fabric-resource-conditions-api-v1 2.3.15+78d798af4f
[Server]           |-- fabric-resource-loader-v0 0.11.21+ee30b13a4f
[Server]           |-- fabric-screen-api-v1 2.0.18+78d798af4f
[Server]           |-- fabric-screen-handler-api-v1 1.3.56+78d798af4f
[Server]           |-- fabric-sound-api-v1 1.0.18+78d798af4f
[Server]           |-- fabric-transfer-api-v1 4.0.12+90f2d7b14f
[Server]           \-- fabric-transitive-access-wideners-v1 5.0.15+78d798af4f
[Server]        - fabric-language-kotlin 1.10.19+kotlin.1.9.23
[Server]           |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
[Server]           |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
[Server]           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
[Server]           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
[Server]           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
[Server]           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
[Server]           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
[Server]           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
[Server]           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
[Server]           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
[Server]           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
[Server]        - fabricloader 0.15.9
[Server]           \-- mixinextras 0.3.5
[Server]        - java 17
[Server]        - jline4mcdsrv 0.5.0
[Server]           |-- com_moandjiezana_toml_toml4j 0.7.2
[Server]           |-- org_jline_jline 3.25.1
[Server]           \-- org_jline_jline-terminal-jansi 3.25.1
[Server]        - lithium 0.12.1
[Server]        - minecraft 1.20.4
[Server]        - skinrestorer 1.2.4
[Server]        - styledplayerlist 3.3.0+1.20.3
[Server]           |-- placeholder-api 2.3.0+1.20.3
[Server]           |-- player-data-api 0.4.0+1.20.3
[Server]           \-- predicate-api 0.3.0+1.20.2
[Server] [19:28:47] [main/ERROR]: Uncaught exception in thread "main"
[Server] java.lang.RuntimeException: An exception occurred when launching the server!
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71) ~[fabric-loader-0.15.9.jar:?]
[Server] Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod enclosure
[Server]        at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:514) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.9.jar:?]
[Server] Caused by: net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
[Server]        at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.lib.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:512) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.9.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.9.jar:?]

**Comment by zly2006** [comment]
你这是source jar，请下载名字不带source的那个文件

**Comment by liuchuanbo0128** [comment]
> 你这是source jar，请下载名字不带source的那个文件

可是modrinth上1.20.4只有一个source版本啊，现在1.20.4还用不了吗

**Comment by liuchuanbo0128** [comment]
![image](https://github.com/zly2006/Enclosure/assets/102268403/661d5b7b-d9df-4741-8945-f7571f215f8c)

**Comment by zly2006** [comment]
我上传错了，非常抱歉，回去改

**Comment by liuchuanbo0128** [comment]
感谢qwq

**Comment by zly2006** [comment]
已更新modrinth

**Comment by liuchuanbo0128** [comment]
ok非常感谢！祝作者生活顺利！
