### ISSUE TITLE
[BUG] GUI Doesnt Display

### ISSUE THREAD

**Issue by TrissieTheHusky** [zly2006/Enclosure#44]
### Check the following items before submitting this issue.

- [X] I am sure that this bug happens in the newest version of Enclosure.
- [X] I am using the official Enclosure, not a fork from this repo.
- [X] I am using a Minecraft version that is still being maintained.

### Describe the bug

I am running 1.21 with Fabric Latest version, I run any gui and I have perms it doesnt display anything at all

### To Reproduce

run /res gui or /enclosure gui

### Expected behavior

show me gui

### Environment

- OS: Windows 11
- MC Version: 1.21
- Version 1.21

### Mod list

![image](https://github.com/user-attachments/assets/c839d440-0965-43ac-a714-d28796638702)

**Comment by zly2006** [comment]
Hi could you help test the latest ci version? 
https://github.com/zly2006/Enclosure/actions/runs/9929756410

Download at artifacts
