### ISSUE TITLE
编辑领地公共权限、玩家权限会被踢出服务器

### ISSUE THREAD

**Issue by chenjunfu2** [zly2006/Enclosure#6]
**描述BUG**
编辑领地公共权限、玩家权限会被踢出服务器。

**重现**
领地公共权限、玩家权限编辑时，只要点击修改权限的按钮，你就会被踢出服务器并获得一条报错信息，具体信息见屏幕截图和日志。

**预期行为**
成功编辑权限，除此之外不发生任何事情。

**屏幕截图**
![1](https://user-images.githubusercontent.com/64954184/236451914-f89fe3aa-ee05-4c45-8a8a-da22e408064c.png)
![2](https://user-images.githubusercontent.com/64954184/236451946-cf821376-350e-48a5-a7fa-8a499d985e84.png)
![3](https://user-images.githubusercontent.com/64954184/236451966-9c82b29a-1056-41df-a1ef-732c026a99ef.png)
![4](https://user-images.githubusercontent.com/64954184/236451982-9d5ec9c9-6c78-4896-85b0-614d0f744747.png)
![5](https://user-images.githubusercontent.com/64954184/236451992-723ed4bb-5400-495b-81ea-04b72bfee534.png)

**环境**
 - 操作系统：Windows 10
 - MC版本：1.19.4-Fabric 0.14.17
 - MOD版本：enclosure-0.1-mc1.19.4

**MC Mod列表**
如：
+ [领地] enclosure-0.1-mc1.19.4.jar
+ fabric-api-0.75.3+1.19.4.jar

**MC日志**
[latest.log](https://github.com/zly2006/Enclosure/files/11405914/latest.log)

- [√] 我确定这个bug在最新版本的Enclosure中会出现。
- [√] 我使用的是官方的版本，而不是这个仓库的分支。
- [√] 我使用的Minecraft版本仍在维护。

**其他上下文**
虽然权限编辑时候点击会被踢出服务器，但是再次进入服务器时，之前的编辑会生效，也就是说权限编辑是成功的，但是会被踢出服务器

**Comment by zly2006** [comment]
请使用最新开发版
