### ISSUE TITLE
领地边界处的箱子会与领地外的箱子合并成大箱子

### ISSUE THREAD

**Issue by chenjunfu2** [zly2006/Enclosure#9]
**描述BUG**
领地边界处的箱子会与领地外的箱子合并成大箱子。

**重现**
在领地边界处，领地内的部分放一个箱子，箱子的侧面对着领地外部，在领地外对着这个箱子放箱子时，这个箱子会和领地外的箱子合并成大箱子。

**预期行为**
这个箱子不与领地外的箱子合并。

**屏幕截图**
![QQ图片20230505191417](https://user-images.githubusercontent.com/64954184/236455299-11e39a03-fd90-4ed3-a8d7-e44b3817f200.png)
![QQ图片20230505191428](https://user-images.githubusercontent.com/64954184/236455311-9e45da51-ee4d-42b8-b81c-455de36e7422.png)
![QQ图片20230505191445](https://user-images.githubusercontent.com/64954184/236455332-0e2c1307-fea8-492b-b5ef-59c5e69ffcd4.png)
![QQ图片20230505191448](https://user-images.githubusercontent.com/64954184/236455350-20934386-301d-475e-b219-5fef739e5a39.png)

**环境**
 - 操作系统：Windows 10
 - MC版本：1.19.4-Fabric 0.14.17
 - MOD版本：enclosure-0.1-mc1.19.4

**MC Mod列表**
+ [领地] enclosure-0.1-mc1.19.4.jar
+ fabric-api-0.75.3+1.19.4.jar

- [√] 我确定这个bug在最新版本的Enclosure中会出现。
- [√] 我使用的是官方的版本，而不是这个仓库的分支。
- [√] 我使用的Minecraft版本仍在维护。

**其他上下文**
如果玩家没有领地内容器权限则打不开这个合并大箱子，但是可以使用漏斗矿车、漏斗等在外侧的大箱子吸走物品，这个吸收过程会影响到领地内被保护的箱子内的物品，同时玩家放在领地外侧的箱子可以被玩家破坏，即便玩家没有领地的破坏权限。

![QQ图片20230505191808](https://user-images.githubusercontent.com/64954184/236455377-f938eeff-e254-4918-ab3d-bf0bc13d061a.png)
![QQ图片20230505191816](https://user-images.githubusercontent.com/64954184/236455410-4d6ff0c7-76e4-481e-9ca4-d7a24ba11dc7.png)
![QQ图片20230505191820](https://user-images.githubusercontent.com/64954184/236455438-f0624da8-7e00-4ac1-98b5-b129eccdd265.png)
![QQ图片20230505191823](https://user-images.githubusercontent.com/64954184/236455476-b1283c6f-40d4-44fb-9032-5f8edf8777b1.png)
![QQ图片20230505191826](https://user-images.githubusercontent.com/64954184/236455489-3cab09af-33cb-4812-aee6-78cecdda386c.png)
![QQ图片20230505191830](https://user-images.githubusercontent.com/64954184/236455507-7ad1f686-5eae-47f0-b25c-375b15cc8f9c.png)

**Comment by zly2006** [comment]
fixed
